/**
 * generated by Xtext 2.9.0
 */
package fr.itemis.xtext.example.kwdl.kwdl.impl;

import fr.itemis.xtext.example.kwdl.kwdl.ActionRulls;
import fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action Rulls</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link fr.itemis.xtext.example.kwdl.kwdl.impl.ActionRullsImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.itemis.xtext.example.kwdl.kwdl.impl.ActionRullsImpl#getLable <em>Lable</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class ActionRullsImpl extends MinimalEObjectImpl.Container implements ActionRulls
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getLable() <em>Lable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLable()
   * @generated
   * @ordered
   */
  protected static final String LABLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLable() <em>Lable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLable()
   * @generated
   * @ordered
   */
  protected String lable = LABLE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionRullsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KwdlPackage.Literals.ACTION_RULLS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KwdlPackage.ACTION_RULLS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLable()
  {
    return lable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLable(String newLable)
  {
    String oldLable = lable;
    lable = newLable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KwdlPackage.ACTION_RULLS__LABLE, oldLable, lable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KwdlPackage.ACTION_RULLS__NAME:
        return getName();
      case KwdlPackage.ACTION_RULLS__LABLE:
        return getLable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KwdlPackage.ACTION_RULLS__NAME:
        setName((String)newValue);
        return;
      case KwdlPackage.ACTION_RULLS__LABLE:
        setLable((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KwdlPackage.ACTION_RULLS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case KwdlPackage.ACTION_RULLS__LABLE:
        setLable(LABLE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KwdlPackage.ACTION_RULLS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case KwdlPackage.ACTION_RULLS__LABLE:
        return LABLE_EDEFAULT == null ? lable != null : !LABLE_EDEFAULT.equals(lable);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", lable: ");
    result.append(lable);
    result.append(')');
    return result.toString();
  }

} //ActionRullsImpl
