/*
 * generated by Xtext 2.9.0
 */
package fr.itemis.xtext.example.kwdl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKwdlScopeProvider extends DelegatingScopeProvider {
}
