/*
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.web

import fr.itemis.xtext.example.test.web.contentAssit.TestContentProposalProvider
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class TestWebModule extends AbstractTestWebModule {
	def Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return TestContentProposalProvider
	}
}
