/*
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import fr.itemis.xtext.example.test.ide.contentassist.antlr.TestParser;
import fr.itemis.xtext.example.test.ide.contentassist.antlr.internal.InternalTestLexer;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link TestWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractTestWebModule extends DefaultWebModule {

	public AbstractTestWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalTestLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return TestParser.class;
	}
	
}
