/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.test;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.itemis.xtext.example.test.test.TestPackage
 * @generated
 */
public interface TestFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TestFactory eINSTANCE = fr.itemis.xtext.example.test.test.impl.TestFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Tgt Script</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tgt Script</em>'.
   * @generated
   */
  TgtScript createTgtScript();

  /**
   * Returns a new object of class '<em>Declare Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declare Variable</em>'.
   * @generated
   */
  DeclareVariable createDeclareVariable();

  /**
   * Returns a new object of class '<em>Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable</em>'.
   * @generated
   */
  Variable createVariable();

  /**
   * Returns a new object of class '<em>After Shell</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>After Shell</em>'.
   * @generated
   */
  AfterShell createAfterShell();

  /**
   * Returns a new object of class '<em>Step Shell</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Step Shell</em>'.
   * @generated
   */
  StepShell createStepShell();

  /**
   * Returns a new object of class '<em>Pre Shell</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pre Shell</em>'.
   * @generated
   */
  PreShell createPreShell();

  /**
   * Returns a new object of class '<em>Tgt Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tgt Statement</em>'.
   * @generated
   */
  TgtStatement createTgtStatement();

  /**
   * Returns a new object of class '<em>Tgt Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tgt Step</em>'.
   * @generated
   */
  TgtStep createTgtStep();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TestPackage getTestPackage();

} //TestFactory
