/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.test;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.itemis.xtext.example.test.test.TestFactory
 * @model kind="package"
 * @generated
 */
public interface TestPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "test";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.itemis.fr/xtext/example/test/Test";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "test";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TestPackage eINSTANCE = fr.itemis.xtext.example.test.test.impl.TestPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.itemis.xtext.example.test.test.impl.TgtScriptImpl <em>Tgt Script</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.itemis.xtext.example.test.test.impl.TgtScriptImpl
   * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getTgtScript()
   * @generated
   */
  int TGT_SCRIPT = 0;

  /**
   * The feature id for the '<em><b>Pre Shell</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_SCRIPT__PRE_SHELL = 0;

  /**
   * The feature id for the '<em><b>Step Shell</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_SCRIPT__STEP_SHELL = 1;

  /**
   * The feature id for the '<em><b>After Shell</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_SCRIPT__AFTER_SHELL = 2;

  /**
   * The feature id for the '<em><b>Declare Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_SCRIPT__DECLARE_VARIABLE = 3;

  /**
   * The number of structural features of the '<em>Tgt Script</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_SCRIPT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.itemis.xtext.example.test.test.impl.DeclareVariableImpl <em>Declare Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.itemis.xtext.example.test.test.impl.DeclareVariableImpl
   * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getDeclareVariable()
   * @generated
   */
  int DECLARE_VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARE_VARIABLE__VARIABLES = 0;

  /**
   * The number of structural features of the '<em>Declare Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARE_VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.itemis.xtext.example.test.test.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.itemis.xtext.example.test.test.impl.VariableImpl
   * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__VALUES = 1;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.itemis.xtext.example.test.test.impl.AfterShellImpl <em>After Shell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.itemis.xtext.example.test.test.impl.AfterShellImpl
   * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getAfterShell()
   * @generated
   */
  int AFTER_SHELL = 3;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_SHELL__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>After Shell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_SHELL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.itemis.xtext.example.test.test.impl.StepShellImpl <em>Step Shell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.itemis.xtext.example.test.test.impl.StepShellImpl
   * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getStepShell()
   * @generated
   */
  int STEP_SHELL = 4;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_SHELL__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Step Shell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STEP_SHELL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.itemis.xtext.example.test.test.impl.PreShellImpl <em>Pre Shell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.itemis.xtext.example.test.test.impl.PreShellImpl
   * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getPreShell()
   * @generated
   */
  int PRE_SHELL = 5;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRE_SHELL__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Pre Shell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRE_SHELL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.itemis.xtext.example.test.test.impl.TgtStatementImpl <em>Tgt Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.itemis.xtext.example.test.test.impl.TgtStatementImpl
   * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getTgtStatement()
   * @generated
   */
  int TGT_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Action Call</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_STATEMENT__ACTION_CALL = 0;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_STATEMENT__COMMENT = 1;

  /**
   * The feature id for the '<em><b>Step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_STATEMENT__STEP = 2;

  /**
   * The number of structural features of the '<em>Tgt Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.itemis.xtext.example.test.test.impl.TgtStepImpl <em>Tgt Step</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.itemis.xtext.example.test.test.impl.TgtStepImpl
   * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getTgtStep()
   * @generated
   */
  int TGT_STEP = 7;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_STEP__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Tgt Step</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TGT_STEP_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link fr.itemis.xtext.example.test.test.TgtScript <em>Tgt Script</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tgt Script</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtScript
   * @generated
   */
  EClass getTgtScript();

  /**
   * Returns the meta object for the containment reference '{@link fr.itemis.xtext.example.test.test.TgtScript#getPreShell <em>Pre Shell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pre Shell</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtScript#getPreShell()
   * @see #getTgtScript()
   * @generated
   */
  EReference getTgtScript_PreShell();

  /**
   * Returns the meta object for the containment reference '{@link fr.itemis.xtext.example.test.test.TgtScript#getStepShell <em>Step Shell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Step Shell</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtScript#getStepShell()
   * @see #getTgtScript()
   * @generated
   */
  EReference getTgtScript_StepShell();

  /**
   * Returns the meta object for the containment reference '{@link fr.itemis.xtext.example.test.test.TgtScript#getAfterShell <em>After Shell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>After Shell</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtScript#getAfterShell()
   * @see #getTgtScript()
   * @generated
   */
  EReference getTgtScript_AfterShell();

  /**
   * Returns the meta object for the containment reference '{@link fr.itemis.xtext.example.test.test.TgtScript#getDeclareVariable <em>Declare Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Declare Variable</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtScript#getDeclareVariable()
   * @see #getTgtScript()
   * @generated
   */
  EReference getTgtScript_DeclareVariable();

  /**
   * Returns the meta object for class '{@link fr.itemis.xtext.example.test.test.DeclareVariable <em>Declare Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declare Variable</em>'.
   * @see fr.itemis.xtext.example.test.test.DeclareVariable
   * @generated
   */
  EClass getDeclareVariable();

  /**
   * Returns the meta object for the containment reference list '{@link fr.itemis.xtext.example.test.test.DeclareVariable#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see fr.itemis.xtext.example.test.test.DeclareVariable#getVariables()
   * @see #getDeclareVariable()
   * @generated
   */
  EReference getDeclareVariable_Variables();

  /**
   * Returns the meta object for class '{@link fr.itemis.xtext.example.test.test.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see fr.itemis.xtext.example.test.test.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link fr.itemis.xtext.example.test.test.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.itemis.xtext.example.test.test.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for the attribute list '{@link fr.itemis.xtext.example.test.test.Variable#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Values</em>'.
   * @see fr.itemis.xtext.example.test.test.Variable#getValues()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Values();

  /**
   * Returns the meta object for class '{@link fr.itemis.xtext.example.test.test.AfterShell <em>After Shell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>After Shell</em>'.
   * @see fr.itemis.xtext.example.test.test.AfterShell
   * @generated
   */
  EClass getAfterShell();

  /**
   * Returns the meta object for the containment reference list '{@link fr.itemis.xtext.example.test.test.AfterShell#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see fr.itemis.xtext.example.test.test.AfterShell#getStatements()
   * @see #getAfterShell()
   * @generated
   */
  EReference getAfterShell_Statements();

  /**
   * Returns the meta object for class '{@link fr.itemis.xtext.example.test.test.StepShell <em>Step Shell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Step Shell</em>'.
   * @see fr.itemis.xtext.example.test.test.StepShell
   * @generated
   */
  EClass getStepShell();

  /**
   * Returns the meta object for the containment reference list '{@link fr.itemis.xtext.example.test.test.StepShell#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see fr.itemis.xtext.example.test.test.StepShell#getStatements()
   * @see #getStepShell()
   * @generated
   */
  EReference getStepShell_Statements();

  /**
   * Returns the meta object for class '{@link fr.itemis.xtext.example.test.test.PreShell <em>Pre Shell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pre Shell</em>'.
   * @see fr.itemis.xtext.example.test.test.PreShell
   * @generated
   */
  EClass getPreShell();

  /**
   * Returns the meta object for the containment reference list '{@link fr.itemis.xtext.example.test.test.PreShell#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see fr.itemis.xtext.example.test.test.PreShell#getStatements()
   * @see #getPreShell()
   * @generated
   */
  EReference getPreShell_Statements();

  /**
   * Returns the meta object for class '{@link fr.itemis.xtext.example.test.test.TgtStatement <em>Tgt Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tgt Statement</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtStatement
   * @generated
   */
  EClass getTgtStatement();

  /**
   * Returns the meta object for the attribute '{@link fr.itemis.xtext.example.test.test.TgtStatement#getActionCall <em>Action Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action Call</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtStatement#getActionCall()
   * @see #getTgtStatement()
   * @generated
   */
  EAttribute getTgtStatement_ActionCall();

  /**
   * Returns the meta object for the attribute '{@link fr.itemis.xtext.example.test.test.TgtStatement#getComment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comment</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtStatement#getComment()
   * @see #getTgtStatement()
   * @generated
   */
  EAttribute getTgtStatement_Comment();

  /**
   * Returns the meta object for the containment reference '{@link fr.itemis.xtext.example.test.test.TgtStatement#getStep <em>Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Step</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtStatement#getStep()
   * @see #getTgtStatement()
   * @generated
   */
  EReference getTgtStatement_Step();

  /**
   * Returns the meta object for class '{@link fr.itemis.xtext.example.test.test.TgtStep <em>Tgt Step</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tgt Step</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtStep
   * @generated
   */
  EClass getTgtStep();

  /**
   * Returns the meta object for the containment reference list '{@link fr.itemis.xtext.example.test.test.TgtStep#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see fr.itemis.xtext.example.test.test.TgtStep#getStatements()
   * @see #getTgtStep()
   * @generated
   */
  EReference getTgtStep_Statements();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TestFactory getTestFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.itemis.xtext.example.test.test.impl.TgtScriptImpl <em>Tgt Script</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.itemis.xtext.example.test.test.impl.TgtScriptImpl
     * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getTgtScript()
     * @generated
     */
    EClass TGT_SCRIPT = eINSTANCE.getTgtScript();

    /**
     * The meta object literal for the '<em><b>Pre Shell</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TGT_SCRIPT__PRE_SHELL = eINSTANCE.getTgtScript_PreShell();

    /**
     * The meta object literal for the '<em><b>Step Shell</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TGT_SCRIPT__STEP_SHELL = eINSTANCE.getTgtScript_StepShell();

    /**
     * The meta object literal for the '<em><b>After Shell</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TGT_SCRIPT__AFTER_SHELL = eINSTANCE.getTgtScript_AfterShell();

    /**
     * The meta object literal for the '<em><b>Declare Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TGT_SCRIPT__DECLARE_VARIABLE = eINSTANCE.getTgtScript_DeclareVariable();

    /**
     * The meta object literal for the '{@link fr.itemis.xtext.example.test.test.impl.DeclareVariableImpl <em>Declare Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.itemis.xtext.example.test.test.impl.DeclareVariableImpl
     * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getDeclareVariable()
     * @generated
     */
    EClass DECLARE_VARIABLE = eINSTANCE.getDeclareVariable();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARE_VARIABLE__VARIABLES = eINSTANCE.getDeclareVariable_Variables();

    /**
     * The meta object literal for the '{@link fr.itemis.xtext.example.test.test.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.itemis.xtext.example.test.test.impl.VariableImpl
     * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__VALUES = eINSTANCE.getVariable_Values();

    /**
     * The meta object literal for the '{@link fr.itemis.xtext.example.test.test.impl.AfterShellImpl <em>After Shell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.itemis.xtext.example.test.test.impl.AfterShellImpl
     * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getAfterShell()
     * @generated
     */
    EClass AFTER_SHELL = eINSTANCE.getAfterShell();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFTER_SHELL__STATEMENTS = eINSTANCE.getAfterShell_Statements();

    /**
     * The meta object literal for the '{@link fr.itemis.xtext.example.test.test.impl.StepShellImpl <em>Step Shell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.itemis.xtext.example.test.test.impl.StepShellImpl
     * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getStepShell()
     * @generated
     */
    EClass STEP_SHELL = eINSTANCE.getStepShell();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STEP_SHELL__STATEMENTS = eINSTANCE.getStepShell_Statements();

    /**
     * The meta object literal for the '{@link fr.itemis.xtext.example.test.test.impl.PreShellImpl <em>Pre Shell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.itemis.xtext.example.test.test.impl.PreShellImpl
     * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getPreShell()
     * @generated
     */
    EClass PRE_SHELL = eINSTANCE.getPreShell();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRE_SHELL__STATEMENTS = eINSTANCE.getPreShell_Statements();

    /**
     * The meta object literal for the '{@link fr.itemis.xtext.example.test.test.impl.TgtStatementImpl <em>Tgt Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.itemis.xtext.example.test.test.impl.TgtStatementImpl
     * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getTgtStatement()
     * @generated
     */
    EClass TGT_STATEMENT = eINSTANCE.getTgtStatement();

    /**
     * The meta object literal for the '<em><b>Action Call</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TGT_STATEMENT__ACTION_CALL = eINSTANCE.getTgtStatement_ActionCall();

    /**
     * The meta object literal for the '<em><b>Comment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TGT_STATEMENT__COMMENT = eINSTANCE.getTgtStatement_Comment();

    /**
     * The meta object literal for the '<em><b>Step</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TGT_STATEMENT__STEP = eINSTANCE.getTgtStatement_Step();

    /**
     * The meta object literal for the '{@link fr.itemis.xtext.example.test.test.impl.TgtStepImpl <em>Tgt Step</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.itemis.xtext.example.test.test.impl.TgtStepImpl
     * @see fr.itemis.xtext.example.test.test.impl.TestPackageImpl#getTgtStep()
     * @generated
     */
    EClass TGT_STEP = eINSTANCE.getTgtStep();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TGT_STEP__STATEMENTS = eINSTANCE.getTgtStep_Statements();

  }

} //TestPackage
