/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.test;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tgt Script</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.itemis.xtext.example.test.test.TgtScript#getPreShell <em>Pre Shell</em>}</li>
 *   <li>{@link fr.itemis.xtext.example.test.test.TgtScript#getStepShell <em>Step Shell</em>}</li>
 *   <li>{@link fr.itemis.xtext.example.test.test.TgtScript#getAfterShell <em>After Shell</em>}</li>
 *   <li>{@link fr.itemis.xtext.example.test.test.TgtScript#getDeclareVariable <em>Declare Variable</em>}</li>
 * </ul>
 *
 * @see fr.itemis.xtext.example.test.test.TestPackage#getTgtScript()
 * @model
 * @generated
 */
public interface TgtScript extends EObject
{
  /**
   * Returns the value of the '<em><b>Pre Shell</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pre Shell</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre Shell</em>' containment reference.
   * @see #setPreShell(PreShell)
   * @see fr.itemis.xtext.example.test.test.TestPackage#getTgtScript_PreShell()
   * @model containment="true"
   * @generated
   */
  PreShell getPreShell();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.test.test.TgtScript#getPreShell <em>Pre Shell</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre Shell</em>' containment reference.
   * @see #getPreShell()
   * @generated
   */
  void setPreShell(PreShell value);

  /**
   * Returns the value of the '<em><b>Step Shell</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Step Shell</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step Shell</em>' containment reference.
   * @see #setStepShell(StepShell)
   * @see fr.itemis.xtext.example.test.test.TestPackage#getTgtScript_StepShell()
   * @model containment="true"
   * @generated
   */
  StepShell getStepShell();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.test.test.TgtScript#getStepShell <em>Step Shell</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step Shell</em>' containment reference.
   * @see #getStepShell()
   * @generated
   */
  void setStepShell(StepShell value);

  /**
   * Returns the value of the '<em><b>After Shell</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>After Shell</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>After Shell</em>' containment reference.
   * @see #setAfterShell(AfterShell)
   * @see fr.itemis.xtext.example.test.test.TestPackage#getTgtScript_AfterShell()
   * @model containment="true"
   * @generated
   */
  AfterShell getAfterShell();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.test.test.TgtScript#getAfterShell <em>After Shell</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>After Shell</em>' containment reference.
   * @see #getAfterShell()
   * @generated
   */
  void setAfterShell(AfterShell value);

  /**
   * Returns the value of the '<em><b>Declare Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declare Variable</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declare Variable</em>' containment reference.
   * @see #setDeclareVariable(DeclareVariable)
   * @see fr.itemis.xtext.example.test.test.TestPackage#getTgtScript_DeclareVariable()
   * @model containment="true"
   * @generated
   */
  DeclareVariable getDeclareVariable();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.test.test.TgtScript#getDeclareVariable <em>Declare Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declare Variable</em>' containment reference.
   * @see #getDeclareVariable()
   * @generated
   */
  void setDeclareVariable(DeclareVariable value);

} // TgtScript
