/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.test;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tgt Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.itemis.xtext.example.test.test.TgtStatement#getActionCall <em>Action Call</em>}</li>
 *   <li>{@link fr.itemis.xtext.example.test.test.TgtStatement#getComment <em>Comment</em>}</li>
 *   <li>{@link fr.itemis.xtext.example.test.test.TgtStatement#getStep <em>Step</em>}</li>
 * </ul>
 *
 * @see fr.itemis.xtext.example.test.test.TestPackage#getTgtStatement()
 * @model
 * @generated
 */
public interface TgtStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Action Call</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action Call</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Call</em>' attribute.
   * @see #setActionCall(String)
   * @see fr.itemis.xtext.example.test.test.TestPackage#getTgtStatement_ActionCall()
   * @model
   * @generated
   */
  String getActionCall();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.test.test.TgtStatement#getActionCall <em>Action Call</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Call</em>' attribute.
   * @see #getActionCall()
   * @generated
   */
  void setActionCall(String value);

  /**
   * Returns the value of the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comment</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' attribute.
   * @see #setComment(String)
   * @see fr.itemis.xtext.example.test.test.TestPackage#getTgtStatement_Comment()
   * @model
   * @generated
   */
  String getComment();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.test.test.TgtStatement#getComment <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' attribute.
   * @see #getComment()
   * @generated
   */
  void setComment(String value);

  /**
   * Returns the value of the '<em><b>Step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Step</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step</em>' containment reference.
   * @see #setStep(TgtStep)
   * @see fr.itemis.xtext.example.test.test.TestPackage#getTgtStatement_Step()
   * @model containment="true"
   * @generated
   */
  TgtStep getStep();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.test.test.TgtStatement#getStep <em>Step</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step</em>' containment reference.
   * @see #getStep()
   * @generated
   */
  void setStep(TgtStep value);

} // TgtStatement
