/*
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTestScopeProvider extends DelegatingScopeProvider {
}
