/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.kwdl.validation;

import fr.itemis.xtext.example.kwdl.validation.AbstractKwdlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class KwdlValidator extends AbstractKwdlValidator {
}
