/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.kwdl.kwdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Rulls</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.itemis.xtext.example.kwdl.kwdl.ActionRulls#getName <em>Name</em>}</li>
 *   <li>{@link fr.itemis.xtext.example.kwdl.kwdl.ActionRulls#getLable <em>Lable</em>}</li>
 * </ul>
 *
 * @see fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage#getActionRulls()
 * @model
 * @generated
 */
public interface ActionRulls extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage#getActionRulls_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.kwdl.kwdl.ActionRulls#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Lable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lable</em>' attribute.
   * @see #setLable(String)
   * @see fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage#getActionRulls_Lable()
   * @model
   * @generated
   */
  String getLable();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.kwdl.kwdl.ActionRulls#getLable <em>Lable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lable</em>' attribute.
   * @see #getLable()
   * @generated
   */
  void setLable(String value);

} // ActionRulls
