/**
 * generated by Xtext 2.9.0
 */
package fr.itemis.xtext.example.kwdl.kwdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Keyword</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link fr.itemis.xtext.example.kwdl.kwdl.Keyword#getName <em>Name</em>}</li>
 *   <li>{@link fr.itemis.xtext.example.kwdl.kwdl.Keyword#getParameters <em>Parameters</em>}</li>
 * </ul>
 * </p>
 *
 * @see fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage#getKeyword()
 * @model
 * @generated
 */
public interface Keyword extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage#getKeyword_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.itemis.xtext.example.kwdl.kwdl.Keyword#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link fr.itemis.xtext.example.kwdl.kwdl.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage#getKeyword_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

} // Keyword
