/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.kwdl.kwdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.itemis.xtext.example.kwdl.kwdl.Model#getActionRulls <em>Action Rulls</em>}</li>
 * </ul>
 *
 * @see fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Action Rulls</b></em>' containment reference list.
   * The list contents are of type {@link fr.itemis.xtext.example.kwdl.kwdl.ActionRulls}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action Rulls</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Rulls</em>' containment reference list.
   * @see fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage#getModel_ActionRulls()
   * @model containment="true"
   * @generated
   */
  EList<ActionRulls> getActionRulls();

} // Model
