/*
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TestAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/itemis/xtext/example/test/parser/antlr/internal/InternalTest.tokens");
	}
}
