/*
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.kwdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KwdlStandaloneSetup extends KwdlStandaloneSetupGenerated {

	def static void doSetup() {
		new KwdlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
