/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.kwdl.ui.contentassist;

import fr.itemis.xtext.example.kwdl.ui.contentassist.AbstractKwdlProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class KwdlProposalProvider extends AbstractKwdlProposalProvider {
}
