/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test;

import fr.itemis.xtext.example.test.TestStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TestStandaloneSetup extends TestStandaloneSetupGenerated {
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type TestStandaloneSetup");
  }
}
