/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test;

import fr.itemis.xtext.example.test.AbstractTestRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TestRuntimeModule extends AbstractTestRuntimeModule {
}
