/*
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TestStandaloneSetup extends TestStandaloneSetupGenerated {

	def static void doSetup() {
		new TestStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
