/*
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TestRuntimeModule extends AbstractTestRuntimeModule {
}
