/*
 * generated by Xtext 2.9.0
 */
package fr.itemis.xtext.example.kwdl.serializer;

import com.google.inject.Inject;
import fr.itemis.xtext.example.kwdl.services.KwdlGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class KwdlSyntacticSequencer extends AbstractSyntacticSequencer {

	protected KwdlGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ActionRulls___IDTerminalRuleCall_4_1_or_STRINGTerminalRuleCall_4_0__a;
	protected AbstractElementAlias match_Parameter___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (KwdlGrammarAccess) access;
		match_ActionRulls___IDTerminalRuleCall_4_1_or_STRINGTerminalRuleCall_4_0__a = new AlternativeAlias(true, true, new TokenAlias(false, false, grammarAccess.getActionRullsAccess().getIDTerminalRuleCall_4_1()), new TokenAlias(false, false, grammarAccess.getActionRullsAccess().getSTRINGTerminalRuleCall_4_0()));
		match_Parameter___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getParameterAccess().getLeftCurlyBracketKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getParameterAccess().getRightCurlyBracketKeyword_3_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSTRINGRule())
			return getSTRINGToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID  		: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	/**
	 * terminal STRING	: 
	 * 			'"' ( '\\' .  | !('\\'|'"') )* '"' |
	 * 			"'" ( '\\' .  | !('\\'|"'") )* "'"
	 * 		;
	 */
	protected String getSTRINGToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\"\"";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ActionRulls___IDTerminalRuleCall_4_1_or_STRINGTerminalRuleCall_4_0__a.equals(syntax))
				emit_ActionRulls___IDTerminalRuleCall_4_1_or_STRINGTerminalRuleCall_4_0__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Parameter___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q.equals(syntax))
				emit_Parameter___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     (STRING | ID)*
	 *
	 * This ambiguous syntax occurs at:
	 *     lable=ID ')' ':' (ambiguity) (rule end)
	 *     name=ID ':' (ambiguity) (rule end)
	 */
	protected void emit_ActionRulls___IDTerminalRuleCall_4_1_or_STRINGTerminalRuleCall_4_0__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) (rule end)
	 */
	protected void emit_Parameter___LeftCurlyBracketKeyword_3_0_RightCurlyBracketKeyword_3_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
