/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.web;

import java.util.concurrent.ExecutorService;

/**
 * Initialization support for running Xtext languages in web applications.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class TestWebSetup /* implements TestStandaloneSetup  */{
  private final /* Provider<ExecutorService> */Object executorServiceProvider;
  
  @Override
  public /* Injector */Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nTestRuntimeModule cannot be resolved."
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules is undefined"
      + "\nInvalid number of arguments. The constructor TestWebModule() is not applicable for the arguments (Provider)"
      + "\ncreateInjector cannot be resolved"
      + "\noverride cannot be resolved"
      + "\nwith cannot be resolved");
  }
}
