/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.web;

import fr.itemis.xtext.example.test.web.AbstractTestWebModule;
import fr.itemis.xtext.example.test.web.contentAssit.TestContentProposalProvider;

/**
 * Use this class to register additional components to be used within the web application.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class TestWebModule extends AbstractTestWebModule {
  public /* Class<? extends IdeContentProposalProvider> */Object bindIdeContentProposalProvider() {
    return TestContentProposalProvider.class;
  }
}
