/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.validation;

import fr.itemis.xtext.example.test.validation.AbstractTestValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TestValidator extends AbstractTestValidator {
}
