/*
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.kwdl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KwdlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/itemis/xtext/example/kwdl/parser/antlr/internal/InternalKwdl.tokens");
	}
}
