/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.generator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class TestGenerator /* implements AbstractGenerator  */{
  @Override
  public void doGenerate(final /* Resource */Object resource, final /* IFileSystemAccess2 */Object fsa, final /* IGeneratorContext */Object context) {
  }
}
