/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.scoping;

import fr.itemis.xtext.example.test.scoping.AbstractTestScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TestScopeProvider extends AbstractTestScopeProvider {
}
