/*
 * generated by Xtext 2.9.0
 */
package fr.itemis.xtext.example.kwdl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractKwdlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(fr.itemis.xtext.example.kwdl.kwdl.KwdlPackage.eINSTANCE);
		return result;
	}
	
}
