/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.kwdl.ui;

import fr.itemis.xtext.example.kwdl.ui.AbstractKwdlUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class KwdlUiModule extends AbstractKwdlUiModule {
  public KwdlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
