/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.test.tests;

import fr.itemis.xtext.example.test.tests.TestInjectorProvider;

/* @RunWith(/* name is null */)
@InjectWith(TestInjectorProvider.class) */@SuppressWarnings("all")
public class TestParsingTest {
  /* @Inject
   */private /* ParseHelper<TgtScript> */Object parseHelper;
  
  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assert is undefined"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved");
  }
}
