/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.kwdl;

import fr.itemis.xtext.example.kwdl.KwdlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class KwdlStandaloneSetup extends KwdlStandaloneSetupGenerated {
  public static void doSetup() {
    KwdlStandaloneSetup _kwdlStandaloneSetup = new KwdlStandaloneSetup();
    _kwdlStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
