/**
 * generated by Xtext 2.9.1
 */
package fr.itemis.xtext.example.kwdl;

import fr.itemis.xtext.example.kwdl.AbstractKwdlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class KwdlRuntimeModule extends AbstractKwdlRuntimeModule {
}
